//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace html5up_dopetrope_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RoomCharge
    {
        public int ID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public bool IsDelete { get; set; }
        public int LowSeasonHoliday { get; set; }
        public int LowSeasonWeekday { get; set; }
        public int HighSeasonHoliday { get; set; }
        public int HighSeasonWeekday { get; set; }
        public int RoomId { get; set; }
        public int ExtraBedCharge { get; set; }
    
        public virtual TB_Room TB_Room { get; set; }
    }
}
