//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace html5up_dopetrope_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RoomBookingOrder
    {
        public int ID { get; set; }
        public System.DateTime OrderDateForm { get; set; }
        public System.DateTime OrderDateTo { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int RoomNum { get; set; }
        public int AdultNum { get; set; }
        public int ChildNum { get; set; }
        public string CustomeName { get; set; }
        public string CustomeEmail { get; set; }
        public string CustomeSex { get; set; }
        public string CustomeTel { get; set; }
        public int TotalAmount { get; set; }
        public string OrderNo { get; set; }
        public bool IsComplete { get; set; }
        public int RoomId { get; set; }
        public bool IsExtraBed { get; set; }
        public int ExtraBadNum { get; set; }
    
        public virtual TB_Room TB_Room { get; set; }
    }
}
