//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace html5up_dopetrope_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Room
    {
        public TB_Room()
        {
            this.TB_RoomBookingOrder = new HashSet<TB_RoomBookingOrder>();
            this.TB_RoomCharge = new HashSet<TB_RoomCharge>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double SquareFootage { get; set; }
        public int MaxCapacity { get; set; }
        public string Facility { get; set; }
        public string Features { get; set; }
        public bool IsDelete { get; set; }
        public string ImgUrl1 { get; set; }
        public string ImgUrl2 { get; set; }
        public string ImgUrl3 { get; set; }
        public string ImgUrl4 { get; set; }
        public string ImgUrl5 { get; set; }
        public int ExtraBed { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<TB_RoomBookingOrder> TB_RoomBookingOrder { get; set; }
        public virtual ICollection<TB_RoomCharge> TB_RoomCharge { get; set; }
    }
}
